import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const today = new Date().toISOString().split("T")[0];
const urls = [
  { loc: "/", priority: "1.00" },
  { loc: "/about-us/" },
  { loc: "/who-we-are/" },
  { loc: "/our-vision-and-mission/" },
  { loc: "/our-history/" },
  { loc: "/our-team/" },
  { loc: "/ac-tonnage-calculator/" },
  { loc: "/services/" },
  { loc: "/faj-price-list/" },
  { loc: "/dubai-ac-service-price-list/" },
  { loc: "/services/plumbing-services-in-dubai/" },
  { loc: "/services/electrical-services-in-dubai/" },
  { loc: "/faqs/" },
  { loc: "/our-portfolio/" },
  { loc: "/blogs/" },
  { loc: "/contact-us/" },
  { loc: "/privacy-policy/" },
  { loc: "/refund-policy/" },
  { loc: "/terms-and-conditions/" },
  { loc: "/career/" },
  { loc: "/testimonials/" },
  { loc: "/b2b-services/" },

  { loc: "/dubai/near-me/" },
  { loc: "/dubai/ac-repair-near-me/" },
  { loc: "/dubai/refrigerator-repair-near-me/" },
  { loc: "/dubai/washing-machine-repair-near-me/" },

  { loc: "/services/air-conditioning-repair/" },
  { loc: "/services/air-conditioning-repair/ac-service/", priority: "0.90" },
  { loc: "/services/air-conditioning-repair/ac-annual-maintenance-contract/" },

  { loc: "/services/home-appliances-repair/", priority: "0.90" },
  { loc: "/services/home-appliances-repair/appliances-repair-service/", priority: "0.90" },
  { loc: "/services/home-appliances-repair/appliances-amc-service/" },
  { loc: "/services/home-appliances-repair/built-in-appliances-repair-service/" },
  { loc: "/services/home-appliances-repair/small-home-appliances-service-center-in-dubai/" },
  { loc: "/services/home-appliances-repair/refrigerator-repair-service/" },
  { loc: "/services/home-appliances-repair/washing-machine-repair-service-dubai/" },
  { loc: "/services/home-appliances-repair/dishwasher-repair-service/" },
  { loc: "/services/home-appliances-repair/oven-repair-service/" },
  { loc: "/services/home-appliances-repair/hob-repair-service/" },
  { loc: "/services/home-appliances-repair/gas-cooker-repair-service/" },
  { loc: "/services/home-appliances-repair/robot-vacuum-cleaner-repair/" },
  { loc: "/services/home-appliances-repair/barbeque-repair-in-dubai-barbeque-maintenance-in-dubai-bbq-service-in-dubai/" },
  { loc: "/services/home-appliances-repair/cigar-humidor-repair/" },
  { loc: "/services/home-appliances-repair/ecovacs-vacuum-cleaner-repair-and-service-in-dubai/" },
  { loc: "/services/home-appliances-repair/roborock-vacuum-cleaner-repair-service-in-dubai/" },

  { loc: "/services/coffee-machine/" },
  { loc: "/services/coffee-machine/coffee-machine-service-center/", priority: "0.90" },
  { loc: "/services/coffee-machine/coffee-machine-repairs/" },
  { loc: "/services/mep-services-in-dubai/", priority: "0.90" },

  { loc: "/services/kitchen-equipment-maintenance/" },
  { loc: "/services/kitchen-equipment-maintenance/commercial-cooking-appliances-repair-service/" },
  { loc: "/services/kitchen-equipment-maintenance/commercial-kitchen-equipment-amc/" },
  { loc: "/services/kitchen-equipment-maintenance/commercial-kitchen-equipment-maintenance-services/" },
  { loc: "/services/kitchen-equipment-maintenance/meat-grinder-repair/" },
  { loc: "/services/kitchen-equipment-maintenance/oven-repair/", priority: "0.90" },
  { loc: "/services/kitchen-equipment-maintenance/rational-commercial-kitchen-equipment-repair-and-maintenance-service-dubai/" },
  { loc: "/services/kitchen-equipment-maintenance/unox-commercial-oven-repair-and-maintenance-service-dubai/" },

  { loc: "/services/refrigeration-equipment/" },
  { loc: "/services/refrigeration-equipment/ice-maker-repair/" },
  { loc: "/services/refrigeration-equipment/commercial-refrigeration-maintenance/", priority: "0.90" },
  { loc: "/services/refrigeration-equipment/commercial-refrigeration-maintenance-contract-services/" },

  { loc: "/services/commercial-dishwasher-repair/" },
  { loc: "/services/laundry-equipment-repair/", priority: "0.90" },

  { loc: "/services/pcb-repair-services/" },

  { loc: "/services/air-conditioning-repair/brands/" },
  { loc: "/services/air-conditioning-repair/brands/aftron/" },
  { loc: "/services/air-conditioning-repair/brands/blue-star/" },
  { loc: "/services/air-conditioning-repair/brands/bryant/" },
  { loc: "/services/air-conditioning-repair/brands/coleman/" },
  { loc: "/services/air-conditioning-repair/brands/cooline/" },
  { loc: "/services/air-conditioning-repair/brands/crafft/" },
  { loc: "/services/air-conditioning-repair/brands/daikool/" },
  { loc: "/services/air-conditioning-repair/brands/daikin/" },
  { loc: "/services/air-conditioning-repair/brands/daewoo/" },
  { loc: "/services/air-conditioning-repair/brands/fujitsu/" },
  { loc: "/services/air-conditioning-repair/brands/goodman/" },
  { loc: "/services/air-conditioning-repair/brands/gree/" },
  { loc: "/services/air-conditioning-repair/brands/haier/" },
  { loc: "/services/air-conditioning-repair/brands/hitachi/" },
  { loc: "/services/air-conditioning-repair/brands/lg/" },
  { loc: "/services/air-conditioning-repair/brands/lennox/" },
  { loc: "/services/air-conditioning-repair/brands/mcquay/" },
  { loc: "/services/air-conditioning-repair/brands/midea/" },
  { loc: "/services/air-conditioning-repair/brands/mitsubishi/" },
  { loc: "/services/air-conditioning-repair/brands/nikai/" },
  { loc: "/services/air-conditioning-repair/brands/o-general/" },
  { loc: "/services/air-conditioning-repair/brands/panasonic/" },
  { loc: "/services/air-conditioning-repair/brands/rheem/" },
  { loc: "/services/air-conditioning-repair/brands/ruud/" },
  { loc: "/services/air-conditioning-repair/brands/samsung/" },
  { loc: "/services/air-conditioning-repair/brands/sanyo/" },
  { loc: "/services/air-conditioning-repair/brands/skm/" },
  { loc: "/services/air-conditioning-repair/brands/sub-zero/" },
  { loc: "/services/air-conditioning-repair/brands/super-general/" },
  { loc: "/services/air-conditioning-repair/brands/supra/" },
  { loc: "/services/air-conditioning-repair/brands/tcl/" },
  { loc: "/services/air-conditioning-repair/brands/toshiba/" },
  { loc: "/services/air-conditioning-repair/brands/trane/" },
  { loc: "/services/air-conditioning-repair/brands/westpoint/" },
  { loc: "/services/air-conditioning-repair/brands/white-westinghouse/" },
  { loc: "/services/air-conditioning-repair/brands/whirlpool/" },
  { loc: "/services/air-conditioning-repair/brands/york/" },

  { loc: "/services/home-appliances-repair/brands/admiral/" },
  { loc: "/services/home-appliances-repair/brands/aeg/" },
  { loc: "/services/home-appliances-repair/brands/aftron/" },
  { loc: "/services/home-appliances-repair/brands/ariston/" },
  { loc: "/services/home-appliances-repair/brands/baumatic/" },
  { loc: "/services/home-appliances-repair/brands/beko/" },
  { loc: "/services/home-appliances-repair/brands/bertazzoni/" },
  { loc: "/services/home-appliances-repair/brands/blomberg/" },
  { loc: "/services/home-appliances-repair/brands/bompani/" },
  { loc: "/services/home-appliances-repair/brands/boston/" },
  { loc: "/services/home-appliances-repair/brands/brandt/" },
  { loc: "/services/home-appliances-repair/brands/candy/" },
  { loc: "/services/home-appliances-repair/brands/bosch/" },
  { loc: "/services/home-appliances-repair/brands/daewoo/" },
  { loc: "/services/home-appliances-repair/brands/de-dietrich/" },
  { loc: "/services/home-appliances-repair/brands/delonghi/" },
  { loc: "/services/home-appliances-repair/brands/electrolux/" },
  { loc: "/services/home-appliances-repair/brands/elica/" },
  { loc: "/services/home-appliances-repair/brands/faber/" },
  { loc: "/services/home-appliances-repair/brands/fagor/" },
  { loc: "/services/home-appliances-repair/brands/fisher-paykel/" },
  { loc: "/services/home-appliances-repair/brands/foster/" },
  { loc: "/services/home-appliances-repair/brands/franke/" },
  { loc: "/services/home-appliances-repair/brands/frigidaire/" },
  { loc: "/services/home-appliances-repair/brands/gaggenau/" },
  { loc: "/services/home-appliances-repair/brands/ge-general-electric/" },
  { loc: "/services/home-appliances-repair/brands/gibson/" },
  { loc: "/services/home-appliances-repair/brands/gorenje/" },
  { loc: "/services/home-appliances-repair/brands/haier/" },
  { loc: "/services/home-appliances-repair/brands/hisense/" },
  { loc: "/services/home-appliances-repair/brands/hitachi/" },
  { loc: "/services/home-appliances-repair/brands/hoover/" },
  { loc: "/services/home-appliances-repair/brands/hotpoint/" },
  { loc: "/services/home-appliances-repair/brands/ifb/" },
  { loc: "/services/home-appliances-repair/brands/indesit/" },
  { loc: "/services/home-appliances-repair/brands/kelvinator/" },
  { loc: "/services/home-appliances-repair/brands/kenmore/" },
  { loc: "/services/home-appliances-repair/brands/kenwood/" },
  { loc: "/services/home-appliances-repair/brands/kitchenaid/" },
  { loc: "/services/home-appliances-repair/brands/kitchenaid-stand-mixer-repair/" },
  { loc: "/services/home-appliances-repair/brands/la-germania/" },
  { loc: "/services/home-appliances-repair/brands/lg/" },
  { loc: "/services/home-appliances-repair/brands/liebherr/" },
  { loc: "/services/home-appliances-repair/brands/marvel/" },
  { loc: "/services/home-appliances-repair/brands/maytag/" },
  { loc: "/services/home-appliances-repair/brands/miele/" },
  { loc: "/services/home-appliances-repair/brands/neff/" },
  { loc: "/services/home-appliances-repair/brands/panasonic/" },
  { loc: "/services/home-appliances-repair/brands/samsung/" },
  { loc: "/services/home-appliances-repair/brands/sanyo/" },
  { loc: "/services/home-appliances-repair/brands/sears/" },
  { loc: "/services/home-appliances-repair/brands/sharp/" },
  { loc: "/services/home-appliances-repair/brands/siemens/" },
  { loc: "/services/home-appliances-repair/brands/smeg/" },
  { loc: "/services/home-appliances-repair/brands/smeg-mixer-repair/" },
  { loc: "/services/home-appliances-repair/brands/speed-queen/" },
  { loc: "/services/home-appliances-repair/brands/sub-zero/" },
  { loc: "/services/home-appliances-repair/brands/teka/" },
  { loc: "/services/home-appliances-repair/brands/terim/" },
  { loc: "/services/home-appliances-repair/brands/thermador/" },
  { loc: "/services/home-appliances-repair/brands/toshiba/" },
  { loc: "/services/home-appliances-repair/brands/unimac/" },
  { loc: "/services/home-appliances-repair/brands/viking/" },
  { loc: "/services/home-appliances-repair/brands/westpoint/" },
  { loc: "/services/home-appliances-repair/brands/white-westinghouse/" },
  { loc: "/services/home-appliances-repair/brands/whirlpool/" },
  { loc: "/services/home-appliances-repair/brands/wolf/" },
  { loc: "/services/home-appliances-repair/brands/zanussi/" },
  { loc: "/services/home-appliances-repair/brands/black-and-decker-repair-service-in-dubai/"},
  { loc: "/services/home-appliances-repair/brands/philips-repair-service-in-dubai/"},
  { loc: "/services/home-appliances-repair/brands/braun-household-appliances-repair-service-in-dubai/"},
  { loc: "/services/home-appliances-repair/brands/dyson-vacuum-cleaner-repair-and-service-in-dubai/"},
  { loc: "/services/home-appliances-repair/brands/sage-coffee-machine-repair-and-service-in-dubai/"},
  { loc: "/services/home-appliances-repair/brands/jura-coffee-machine-repair-and-service-in-dubai/"},
  { loc: "/services/home-appliances-repair/brands/karcher-vacuum-cleaner-repair-and-service-in-dubai/"},
  { loc: "/services/home-appliances-repair/brands/ice-cream-machine-repair-and-service-in-dubai/"},

  { loc: "/services/air-conditioning-repair/coverage-area/" },
  { loc: "/services/air-conditioning-repair/coverage-area/academy-city/" },
  { loc: "/services/air-conditioning-repair/coverage-area/al-aweer/" },
  { loc: "/services/air-conditioning-repair/coverage-area/al-badaa/" },
  { loc: "/services/air-conditioning-repair/coverage-area/al-bada/" },
  { loc: "/services/air-conditioning-repair/coverage-area/al-barari/" },
  { loc: "/services/air-conditioning-repair/coverage-area/al-barsha/" },
  { loc: "/services/air-conditioning-repair/coverage-area/al-barsha-south/" },
  { loc: "/services/air-conditioning-repair/coverage-area/al-furjan/" },
  { loc: "/services/air-conditioning-repair/coverage-area/al-jafiliya/" },
  { loc: "/services/air-conditioning-repair/coverage-area/al-karama/" },
  { loc: "/services/air-conditioning-repair/coverage-area/al-khawaneej/" },
  { loc: "/services/air-conditioning-repair/coverage-area/al-mamzar/" },
  { loc: "/services/air-conditioning-repair/coverage-area/al-manara/" },
  { loc: "/services/air-conditioning-repair/coverage-area/al-mirdif/" },
  { loc: "/services/air-conditioning-repair/coverage-area/al-mizhar/" },
  { loc: "/services/air-conditioning-repair/coverage-area/al-quoz/" },
  { loc: "/services/air-conditioning-repair/coverage-area/al-quoz-industrial-area/" },
  { loc: "/services/air-conditioning-repair/coverage-area/al-qusais/" },
  { loc: "/services/air-conditioning-repair/coverage-area/al-raffa/" },
  { loc: "/services/air-conditioning-repair/coverage-area/al-rashidiya/" },
  { loc: "/services/air-conditioning-repair/coverage-area/al-safa/" },
  { loc: "/services/air-conditioning-repair/coverage-area/al-satwa/" },
  { loc: "/services/air-conditioning-repair/coverage-area/al-sufouh/" },
  { loc: "/services/air-conditioning-repair/coverage-area/al-tawar/" },
  { loc: "/services/air-conditioning-repair/coverage-area/al-waha-community/" },
  { loc: "/services/air-conditioning-repair/coverage-area/al-warqa/" },
  { loc: "/services/air-conditioning-repair/coverage-area/al-wasl/" },
  { loc: "/services/air-conditioning-repair/coverage-area/arabian-ranches/" },
  { loc: "/services/air-conditioning-repair/coverage-area/arabian-ranches-2/" },
  { loc: "/services/air-conditioning-repair/coverage-area/bay-square/" },
  { loc: "/services/air-conditioning-repair/coverage-area/bur-dubai/" },
  { loc: "/services/air-conditioning-repair/coverage-area/burj-khalifa-lake/" },
  { loc: "/services/air-conditioning-repair/coverage-area/business-bay/" },
  { loc: "/services/air-conditioning-repair/coverage-area/cedre-villas-silicon-oasis-dubai/" },
  { loc: "/services/air-conditioning-repair/coverage-area/damac-hills/" },
  { loc: "/services/air-conditioning-repair/coverage-area/deira/" },
  { loc: "/services/air-conditioning-repair/coverage-area/difc/" },
  { loc: "/services/air-conditioning-repair/coverage-area/dip/" },
  { loc: "/services/air-conditioning-repair/coverage-area/discovery-gardens/" },
  { loc: "/services/air-conditioning-repair/coverage-area/downtown/" },
  { loc: "/services/air-conditioning-repair/coverage-area/dubai-healthcare-city/" },
  { loc: "/services/air-conditioning-repair/coverage-area/dubai-hills-estate/" },
  { loc: "/services/air-conditioning-repair/coverage-area/dubai-international-financial-centre/" },
  { loc: "/services/air-conditioning-repair/coverage-area/dubai-internet-city/" },
  { loc: "/services/air-conditioning-repair/coverage-area/dubai-investments-park/" },
  { loc: "/services/air-conditioning-repair/coverage-area/dubai-marina/" },
  { loc: "/services/air-conditioning-repair/coverage-area/dubai-production-city/" },
  { loc: "/services/air-conditioning-repair/coverage-area/dubai-silicon-oasis/" },
  { loc: "/services/air-conditioning-repair/coverage-area/dubai-sport-city/" },
  { loc: "/services/air-conditioning-repair/coverage-area/dubai-studio-city/" },
  { loc: "/services/air-conditioning-repair/coverage-area/dubailand-mazaya-queue/" },
  { loc: "/services/air-conditioning-repair/coverage-area/dubailand-the-villa-point/" },
  { loc: "/services/air-conditioning-repair/coverage-area/emirates-hills/" },
  { loc: "/services/air-conditioning-repair/coverage-area/flamingo-villas/" },
  { loc: "/services/air-conditioning-repair/coverage-area/hudaiba/" },
  { loc: "/services/air-conditioning-repair/coverage-area/impz/" },
  { loc: "/services/air-conditioning-repair/coverage-area/index-tower-difc/" },
  { loc: "/services/air-conditioning-repair/coverage-area/jafza/" },
  { loc: "/services/air-conditioning-repair/coverage-area/jbr/" },
  { loc: "/services/air-conditioning-repair/coverage-area/jebel-ali/" },
  { loc: "/services/air-conditioning-repair/coverage-area/jebel-ali-dip/" },
  { loc: "/services/air-conditioning-repair/coverage-area/jebel-ali-free-zone/" },
  { loc: "/services/air-conditioning-repair/coverage-area/jebel-ali-industrial-area/" },
  { loc: "/services/air-conditioning-repair/coverage-area/jebel-ali-village/" },
  { loc: "/services/air-conditioning-repair/coverage-area/jge/" },
  { loc: "/services/air-conditioning-repair/coverage-area/jlt/" },
  { loc: "/services/air-conditioning-repair/coverage-area/jumeirah/" },
  { loc: "/services/air-conditioning-repair/coverage-area/jumeirah-beach-residence/" },
  { loc: "/services/air-conditioning-repair/coverage-area/jumeirah-golf-estates/" },
  { loc: "/services/air-conditioning-repair/coverage-area/jumeirah-heights/" },
  { loc: "/services/air-conditioning-repair/coverage-area/jumeirah-islands/" },
  { loc: "/services/air-conditioning-repair/coverage-area/jumeirah-lake-towers/" },
  { loc: "/services/air-conditioning-repair/coverage-area/jumeirah-park/" },
  { loc: "/services/air-conditioning-repair/coverage-area/jumeirah-village/" },
  { loc: "/services/air-conditioning-repair/coverage-area/jvc/" },
  { loc: "/services/air-conditioning-repair/coverage-area/jvt/" },
  { loc: "/services/air-conditioning-repair/coverage-area/knowledge-village/" },
  { loc: "/services/air-conditioning-repair/coverage-area/layan-community/" },
  { loc: "/services/air-conditioning-repair/coverage-area/limestone-house-difc/" },
  { loc: "/services/air-conditioning-repair/coverage-area/mankhool/" },
  { loc: "/services/air-conditioning-repair/coverage-area/media-city/" },
  { loc: "/services/air-conditioning-repair/coverage-area/motor-city/" },
  { loc: "/services/air-conditioning-repair/coverage-area/mudon/" },
  { loc: "/services/air-conditioning-repair/coverage-area/nad-al-hammar/" },
  { loc: "/services/air-conditioning-repair/coverage-area/nad-al-sheba/" },
  { loc: "/services/air-conditioning-repair/coverage-area/old-town-dubai/" },
  { loc: "/services/air-conditioning-repair/coverage-area/oud-metha/" },
  { loc: "/services/air-conditioning-repair/coverage-area/palm-jumeirah/" },
  { loc: "/services/air-conditioning-repair/coverage-area/ras-al-khor-industrial-area/" },
  { loc: "/services/air-conditioning-repair/coverage-area/remraam/" },
  { loc: "/services/air-conditioning-repair/coverage-area/remraam-2/" },
  { loc: "/services/air-conditioning-repair/coverage-area/south-ridge/" },
  { loc: "/services/air-conditioning-repair/coverage-area/the-gardens/" },
  { loc: "/services/air-conditioning-repair/coverage-area/the-greens/" },
  { loc: "/services/air-conditioning-repair/coverage-area/the-lakes/" },
  { loc: "/services/air-conditioning-repair/coverage-area/the-meadows/" },
  { loc: "/services/air-conditioning-repair/coverage-area/the-ritz-carlton-difc/" },
  { loc: "/services/air-conditioning-repair/coverage-area/the-springs/" },
  { loc: "/services/air-conditioning-repair/coverage-area/the-views/" },
  { loc: "/services/air-conditioning-repair/coverage-area/the-villa/" },
  { loc: "/services/air-conditioning-repair/coverage-area/town-square/" },
  { loc: "/services/air-conditioning-repair/coverage-area/umm-al-sheif/" },
  { loc: "/services/air-conditioning-repair/coverage-area/umm-ramool/" },
  { loc: "/services/air-conditioning-repair/coverage-area/umm-suqeim/" },
  { loc: "/services/air-conditioning-repair/coverage-area/victory-heights/" },

  { loc: "/services/home-appliances-repair/coverage-area/al-badaa/" },
  { loc: "/services/home-appliances-repair/coverage-area/al-bada/" },
  { loc: "/services/home-appliances-repair/coverage-area/al-barari/" },
  { loc: "/services/home-appliances-repair/coverage-area/al-barsha/" },
  { loc: "/services/home-appliances-repair/coverage-area/al-barsha-south/" },
  { loc: "/services/home-appliances-repair/coverage-area/al-furjan/" },
  { loc: "/services/home-appliances-repair/coverage-area/al-ghadeer-community/" },
  { loc: "/services/home-appliances-repair/coverage-area/al-jafiliya/" },
  { loc: "/services/home-appliances-repair/coverage-area/al-karama/" },
  { loc: "/services/home-appliances-repair/coverage-area/al-mamzar/" },
  { loc: "/services/home-appliances-repair/coverage-area/al-manara/" },
  { loc: "/services/home-appliances-repair/coverage-area/al-mizhar/" },
  { loc: "/services/home-appliances-repair/coverage-area/al-quoz/" },
  { loc: "/services/home-appliances-repair/coverage-area/al-raffa/" },
  { loc: "/services/home-appliances-repair/coverage-area/al-safa/" },
  { loc: "/services/home-appliances-repair/coverage-area/al-satwa/" },
  { loc: "/services/home-appliances-repair/coverage-area/al-sufouh/" },
  { loc: "/services/home-appliances-repair/coverage-area/al-waha-community/" },
  { loc: "/services/home-appliances-repair/coverage-area/al-wasl/" },
  { loc: "/services/home-appliances-repair/coverage-area/arabian-ranches/" },
  { loc: "/services/home-appliances-repair/coverage-area/arabian-ranches-2/" },
  { loc: "/services/home-appliances-repair/coverage-area/bur-dubai/" },
  { loc: "/services/home-appliances-repair/coverage-area/business-bay/" },
  { loc: "/services/home-appliances-repair/coverage-area/cedre-villas-silicon-oasis-dubai/" },
  { loc: "/services/home-appliances-repair/coverage-area/damac-hills/" },
  { loc: "/services/home-appliances-repair/coverage-area/deira/" },
  { loc: "/services/home-appliances-repair/coverage-area/difc/" },
  { loc: "/services/home-appliances-repair/coverage-area/dip/" },
  { loc: "/services/home-appliances-repair/coverage-area/discovery-gardens/" },
  { loc: "/services/home-appliances-repair/coverage-area/dubai-healthcare-city/" },
  { loc: "/services/home-appliances-repair/coverage-area/dubai-hills-estate/" },
  { loc: "/services/home-appliances-repair/coverage-area/dubai-internet-city/" },
  { loc: "/services/home-appliances-repair/coverage-area/dubai-investments-park/" },
  { loc: "/services/home-appliances-repair/coverage-area/dubai-marina/" },
  { loc: "/services/home-appliances-repair/coverage-area/dubai-media-city/" },
  { loc: "/services/home-appliances-repair/coverage-area/dubai-motor-city/" },
  { loc: "/services/home-appliances-repair/coverage-area/dubai-production-city/" },
  { loc: "/services/home-appliances-repair/coverage-area/dubai-silicon-oasis/" },
  { loc: "/services/home-appliances-repair/coverage-area/dubai-sports-city/" },
  { loc: "/services/home-appliances-repair/coverage-area/dubai-studio-city/" },
  { loc: "/services/home-appliances-repair/coverage-area/dubailand-mazaya/" },
  { loc: "/services/home-appliances-repair/coverage-area/dubailand-mazaya-queue-point/" },
  { loc: "/services/home-appliances-repair/coverage-area/dubailand-the-villa/" },
  { loc: "/services/home-appliances-repair/coverage-area/emirates-hills/" },
  { loc: "/services/home-appliances-repair/coverage-area/falcon-city-dubai/" },
  { loc: "/services/home-appliances-repair/coverage-area/flamingo-villas-dubai/" },
  { loc: "/services/home-appliances-repair/coverage-area/hudaiba/" },
  { loc: "/services/home-appliances-repair/coverage-area/impz/" },
  { loc: "/services/home-appliances-repair/coverage-area/index-tower-difc/" },
  { loc: "/services/home-appliances-repair/coverage-area/international-media-and-production-zone/" },
  { loc: "/services/home-appliances-repair/coverage-area/jbr/" },
  { loc: "/services/home-appliances-repair/coverage-area/jbr-dubai/" },
  { loc: "/services/home-appliances-repair/coverage-area/jebel-ali/" },
  { loc: "/services/home-appliances-repair/coverage-area/jebel-ali-dip/" },
  { loc: "/services/home-appliances-repair/coverage-area/jebel-ali-free-zone/" },
  { loc: "/services/home-appliances-repair/coverage-area/jebel-ali-industrial-area/" },
  { loc: "/services/home-appliances-repair/coverage-area/jebel-ali-village/" },
  { loc: "/services/home-appliances-repair/coverage-area/jge/" },
  { loc: "/services/home-appliances-repair/coverage-area/jlt/" },
  { loc: "/services/home-appliances-repair/coverage-area/jumeirah/" },
  { loc: "/services/home-appliances-repair/coverage-area/jumeirah-beach-residence/" },
  { loc: "/services/home-appliances-repair/coverage-area/jumeirah-dubai/" },
  { loc: "/services/home-appliances-repair/coverage-area/jumeirah-golf-estates/" },
  { loc: "/services/home-appliances-repair/coverage-area/jumeirah-heights/" },
  { loc: "/services/home-appliances-repair/coverage-area/jumeirah-islands/" },
  { loc: "/services/home-appliances-repair/coverage-area/jumeirah-lake-towers/" },
  { loc: "/services/home-appliances-repair/coverage-area/jumeirah-park/" },
  { loc: "/services/home-appliances-repair/coverage-area/jumeirah-village/" },
  { loc: "/services/home-appliances-repair/coverage-area/jumeirah-village-circle/" },
  { loc: "/services/home-appliances-repair/coverage-area/jumeirah-village-triangle/" },
  { loc: "/services/home-appliances-repair/coverage-area/jvc/" },
  { loc: "/services/home-appliances-repair/coverage-area/jvt/" },
  { loc: "/services/home-appliances-repair/coverage-area/layan-community/" },
  { loc: "/services/home-appliances-repair/coverage-area/mankhool/" },
  { loc: "/services/home-appliances-repair/coverage-area/mudon/" },
  { loc: "/services/home-appliances-repair/coverage-area/nad-al-sheba/" },
  { loc: "/services/home-appliances-repair/coverage-area/oud-metha/" },
  { loc: "/services/home-appliances-repair/coverage-area/palm-jumeirah/" },
  { loc: "/services/home-appliances-repair/coverage-area/remraam/" },
  { loc: "/services/home-appliances-repair/coverage-area/the-gardens/" },
  { loc: "/services/home-appliances-repair/coverage-area/the-greens/" },
  { loc: "/services/home-appliances-repair/coverage-area/the-lakes/" },
  { loc: "/services/home-appliances-repair/coverage-area/the-limestone-house-difc/" },
  { loc: "/services/home-appliances-repair/coverage-area/the-meadows/" },
  { loc: "/services/home-appliances-repair/coverage-area/the-ritz-carlton-difc/" },
  { loc: "/services/home-appliances-repair/coverage-area/the-springs/" },
  { loc: "/services/home-appliances-repair/coverage-area/the-views/" },
  { loc: "/services/home-appliances-repair/coverage-area/the-villa/" },
  { loc: "/services/home-appliances-repair/coverage-area/town-dubai/" },
  { loc: "/services/home-appliances-repair/coverage-area/town-square/" },
  { loc: "/services/home-appliances-repair/coverage-area/tecom/" },
  { loc: "/services/home-appliances-repair/coverage-area/umm-al-sheif/" },
  { loc: "/services/home-appliances-repair/coverage-area/umm-suqeim/" },
  { loc: "/services/home-appliances-repair/coverage-area/victory-heights/" },

  { loc: "/blog/swift-solutions-refrigerator-repair-near-me-for-quick-fixes/"},
  { loc: "/blog/hvac-contractor-in-dubai-your-ultimate-guide-2023/"},
  { loc: "/blog/top-loading-washing-machines-a-complete-guidelines/"},
  { loc: "/blog/its-time-for-an-ac-cleaning/"},
  { loc: "/blog/front-loading-washing-machines/"},
  { loc: "/blog/the-gas-cooker-a-reliable-appliance-for-modern-kitchens/"},
  { loc: "/blog/ai-made-automatic-office-coffee-machines-are-future/"},
  { loc: "/blog/what-is-ac-filter/"},
  { loc: "/blog/how-to-set-ac-temperature-for-cooling/"},
  { loc: "/blog/how-to-clean-ac-filter-for-all-types-a-step-by-step-guide/"},
  { loc: "/blog/10-common-ac-problems-and-how-to-fix-them/"},
  { loc: "/blog/how-to-clean-washing-machine/"},
  { loc: "/blog/how-to-save-money-on-ac/"},
  { loc: "/blog/how-to-choose-the-best-air-conditioner-for-home/"},
  { loc: "/blog/extend-ac-lifespan-tips/"},
  { loc: "/blog/ac-repair-maintenance-difference/"},
  { loc: "/blog/ac-maintenance-cost-guide-dubai/"},
  { loc: "/blog/portable-air-conditioners-guide-2024/"},
  { loc: "/blog/gree-ac-wifi-setup/"},
  { loc: "/blog/how-to-clean-daikin-ac-indoor-unit/"},
  { loc: "/blog/delonghi-coffee-machine-faqs-answered/"},
  { loc: "/blog/benefits-of-smart-thermostats/"},
  { loc: "/blog/dubai-heatwave-tips-ac-importance/"},
  { loc: "/blog/how-to-choose-the-right-ac-repair-service/"},
  { loc: "/blog/how-to-reset-o-general-ac/"},
  { loc: "/blog/how-to-clean-bosch-washing-machine/"},
  { loc: "/blog/safe-successful-kitchen-appliance-installation/"},
  { loc: "/blog/how-to-clean-ac-condenser/"},
  { loc: "/blog/midea-air-conditioner-maintenance-guide/"},
  { loc: "/blog/dishwasher-cleaning-guide/"},
  { loc: "/blog/how-bagless-vacuum-cleaner-work/"},
  { loc: "/blog/types-of-air-conditioners/"},
  { loc: "/blog/refrigerator-inverter-technology/"},
  { loc: "/blog/is-air-fryer-healthy/"},
  { loc: "/blog/top-10-signs-you-need-ac-repair-in-dubai/"},
  { loc: "/blog/top-10-signs-your-ac-needs-maintenance-in-dubai/"},
  { loc: "/blog/top-10-signs-you-need-ac-service-in-dubai/"},
  { loc: "/blog/washing-machine-problems-and-solutions-dubai/"},
  { loc: "/blog/how-to-clean-your-oven/"},
  { loc: "/blog/espresso-machine-cleaning-schedule-and-how-to-do-it/"},
  { loc: "/blog/a-guide-to-diy-refrigerator-maintenance-at-home-keep-your-fridge-running-like-new/"},
  { loc: "/blog/10-coffee-machine-problems-and-how-to-diy-fix-them-like-a-pro/"},
  { loc: "/blog/how-to-choose-a-reliable-technical-service-provider-uae/"},
  { loc: "/blog/the-complete-handbook-for-maintaining-a-dust-free-air-conditioner-in-dubai/"},
  { loc: "/blog/what-is-vent-mode/"},
  { loc: "/blog/how-ac-filter-boost-coling-perrformance-and-air-quality/"},
  { loc: "/blog/what-is-the-ideal-room-temperature-for-comfortable-living-across-different-ages-including-children-and-adults/"},
  { loc: "/blog/ac-repair-dubai-questions-before-hiring-ac-repair-companies-dubai/"},
  { loc: "/blog/how-to-clean-an-air-conditioner-ac-drain-line-for-better-cooling-performance/"},
  { loc: "/blog/ac-compressor-replacement-signs-causes-when-to-replace/"},
  { loc: "/blog/repair-or-replace-what-to-do-with-a-broken-washing-machine-in-dubai/"},
  { loc: "/blog/the-ultimate-guide-to-ac-maintenance-in-dubai-for-Long-lasting-cooling-performance/"},
  { loc: "/blog/how-do-you-clean-a-refrigerator-complete-guide-to-refrigerator-maintenance/"},
  { loc: "/blog/how-to-calculate-ac-tonnage-for-a-room-complete-guide-to-ac-tonnage-calculation/"},
  { loc: "/blog/the-ultimate-guide-to-ac-service-for-healthier-air-and-better-indoor-air-quality/"},
  { loc: "/blog/the-ultimate-guide-to-commercial-kitchen-equipment-for-eid-al-fitr-2026-in-UAE/"},
  { loc: "/blog/the-ultimate-guide-to-refrigerator-temperature-for-food-medicines-safety/"},
  { loc: "/blog/the-ultimate-guide-to-refrigerator-repair-protect-your-familys-health-with-proper-cooling/"},
  { loc: "/blog/best-temperature-setting-for-restaurants-display-fridges-and-chillers-understanding-restaurant-refrigeration-temperature/"},
  { loc: "/blog/humidifier-vs-dehumidifier-what-do-you-need-for-better-air-quality/"},
  { loc: "/blog/cake-storage-temperature-guide-best-temperature-for-fresh-cakes/"},
  { loc: "/blog/the-ultimate-guide-to-data-center-temperature-best-temperature-setting-for-data-center-server-rooms/"},
  { loc: "/blog/how-to-do-ac-service-easy-diy-guide-for-beginners/"},
  { loc: "/blog/effect-of-high-temperature-and-climate-change-on-health-in-dubai-uae/"},
  { loc: "/blog/how-do-you-clean-a-refrigerator-complete-guide-to-refrigerator-cleaning-and-maintenance/"},
  { loc: "/blog/washing-machine-repair-common-problems-causes-and-solutions/"},
  { loc: "/blog/the-ultimate-guide-to-commercial-dishwasher-repair-in-dubai/"},
  { loc: "/blog/the-ultimate-guide-to-commercial-ice-maker-repair-in-dubai/"},
  { loc: "/blog/the-ultimate-guide-to-coffee-machine-repair-dubai-for-cafes-and-homes/"},
  { loc: "/blog/most-common-issues-in-commercial-coffee-machines-uae/"},
  { loc: "/blog/drinking-water-guide-for-peak-summer-in-dubai-uae/"},
  { loc: "/blog/why-skincare-and-ac-maintenance-go-hand-in-hand-in-dubai-harsh-climate/"},
  { loc: "/blog/best-ac-maintenance-tips-for-the-hot-summer-in-dubai-2026/"},
  { loc: "/blog/how-to-survive-the-hottest-summer-in-uae-dubai-2026/"},
  { loc: "/blog/how-an-annual-ac-maintenance-contract-saves-you-money/"},
  { loc: "/blog/why-your-ac-is-not-cooling-top-10-causes-expert-fixes/" },
  { loc: "/blog/a-complete-guide-on-washing-machine-service/"},
  { loc: "/blog/what-is-an-ac-filter-a-complete-guide-2026/"},
  { loc: "/blog/how-to-find-genuine-appliances-spare-parts-in-the-uae/"},
  { loc: "/blog/how-to-fix-a-vacuum-cleaner-a-step-by-step-guide/"},
  { loc: "/services/air-conditioning-repair/\u062a\u0635\u0644\u064a\u062d-\u0645\u0643\u064a\u0641\u0627\u062a-\u0627\u0644\u0647\u0648\u0627\u0621-\u062e\u062f\u0645\u0629-\u0648\u0635\u064a\u0627\u0646\u0629-\u062f\u0628\u064a/" },

  { loc: "/orphan/" },
];

const BASE_URL = "https://www.fajservices.ae";

const seen = new Set();
const uniqueUrls = urls.filter(({ loc }) => {
  if (seen.has(loc)) return false;
  seen.add(loc);
  return true;
});

const xmlEntries = uniqueUrls
  .map(({ loc, priority = "0.80" }) => `  <url>
    <loc>${BASE_URL}${loc}</loc>
    <lastmod>${today}</lastmod>
    <priority>${priority}</priority>
  </url>`)
  .join("\n");

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${xmlEntries}
</urlset>`;

const outputPath = path.resolve(__dirname, "public/sitemap.xml");

try {
  fs.writeFileSync(outputPath, sitemap, "utf-8");
  console.log(` Sitemap generated successfully!`);
  console.log(`   Date: ${today}`);
  console.log(`   Total URLs: ${uniqueUrls.length}`);
  console.log(`   Output: ${outputPath}`);
} catch (err) {
  console.error(" Error writing sitemap:", err.message);
  process.exit(1);
}
